baseURL = "/"
languageCode = "en-us"
title = "Furnace and Fugue"
theme = "atalanta"
assetDir = "assets"
disableLiveReload = true
disableKinds = [
  "taxonomy",
  "taxonomyTerm",
  "RSS",
  "sitemap",
  "robotsTXT",
  "404"
]